//
//  AutoGenerateDescriptionPluginProd.h
//  AutoGenerateDescriptionPluginProd
//
//  Created by adam smith on 2/17/15.
//  Copyright (c) 2015 adam smith. All rights reserved.
//

#import <AppKit/AppKit.h>

@interface AutoGenerateDescriptionPluginProd : NSObject

+ (instancetype)sharedPlugin;

@property (nonatomic, strong, readonly) NSBundle* bundle;
@end