//
//  AutoGenerateDescriptionPluginProd.m
//  AutoGenerateDescriptionPluginProd
//
//  Created by adam smith on 2/17/15.
//  Copyright (c) 2015 adam smith. All rights reserved.
//

#import "AutoGenerateDescriptionPluginProd.h"
#import "DescriptionGenerator.h"

static AutoGenerateDescriptionPluginProd *sharedPlugin;

@interface AutoGenerateDescriptionPluginProd()

@property (nonatomic, strong, readwrite) NSBundle *bundle;
@end

@implementation AutoGenerateDescriptionPluginProd

+ (void)pluginDidLoad:(NSBundle *)plugin
{
    static dispatch_once_t onceToken;
    NSString *currentApplicationName = [[NSBundle mainBundle] infoDictionary][@"CFBundleName"];
    if ([currentApplicationName isEqual:@"Xcode"]) {
        dispatch_once(&onceToken, ^{
            sharedPlugin = [[self alloc] initWithBundle:plugin];
        });
    }
}

+ (instancetype)sharedPlugin
{
    return sharedPlugin;
}

- (id)initWithBundle:(NSBundle *)plugin
{
    if (self = [super init]) {
        // reference to plugin's bundle, for resource access
        self.bundle = plugin;
        
        // Create menu items, initialize UI, etc.
        
        if ([[NSApplication sharedApplication] mainMenu] != nil) {
            [self insertItemMenu];
        } else {
            [[NSApplication sharedApplication] addObserver:self forKeyPath:@"mainMenu" options:NSKeyValueObservingOptionNew context:NULL];
        }
    }
    return self;
}

- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary *)change context:(void *)context {
    if ([keyPath isEqualToString:@"mainMenu"]) {
        [self insertItemMenu];
    }
}

- (void)insertItemMenu {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        NSMenuItem *actionMenuItem = [[NSMenuItem alloc] initWithTitle:@"Make Description" action:@selector(doMenuAction) keyEquivalent:@"p"];
        [actionMenuItem setTarget:self];
        [actionMenuItem setKeyEquivalentModifierMask:NSControlKeyMask];
        
        NSMenuItem *menuItem = [[NSApp mainMenu] itemWithTitle:@"Edit"];
        [[menuItem submenu] addItem:[NSMenuItem separatorItem]];
        [[menuItem submenu] addItem:actionMenuItem];
    });
}

// Sample Action, for menu item:
- (void)doMenuAction
{
    DescriptionGenerator *generator = [DescriptionGenerator new];
    [generator generateDescription];
}

- (void)dealloc
{
    [[NSNotificationCenter defaultCenter] removeObserver:self];
}

@end
