//
//  DescriptionGenerator.h
//  AutoGenerateDescriptionPluginProd
//
//  Created by adam smith on 2/17/15.
//  Copyright (c) 2015 adam smith. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "RegExCategories.h"
#import "DTXcodeHeaders.h"
#import "DTXcodeUtils.h"

@interface DescriptionGenerator : NSObject

- (void)generateDescription;

@end
